from dotenv import load_dotenv
from langchain_openai import ChatOpenAI

# Load the API key from the .env file
load_dotenv()

# Connect to the OpenAI model
llm = ChatOpenAI(model="gpt-4o-mini")

# Ask for exactly 5 healthy breakfast ideas
prompt = """
Give me exactly 5 healthy breakfast ideas.
Use a numbered list, one line per idea, with no preamble.
"""

# Send the prompt to the model
reply = llm.invoke(prompt)

# extracts and prints only the text generated by the AI.
print(reply.content)